# CONFIGURATION BASE DE DONNÉES (WAMP/MySQL)


spring.datasource.url=jdbc:mysql://localhost:3306/gestion_evaluations?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# CONFIGURATION JPA / HIBERNATE


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# CONFIGURATION THYMELEAF (MVC)


# Cache désactivé en développement (rechargement auto)
spring.thymeleaf.cache=false
# Préfixe des templates (défaut: classpath:/templates/)
spring.thymeleaf.prefix=classpath:/templates/
# Suffixe des templates (défaut: .html)
spring.thymeleaf.suffix=.html


# CONFIGURATION SERVEUR


server.port=8081


# CONFIGURATION UPLOAD FICHIERS


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.corriges.dossier=corriges